### ISSUE TITLE
Finalise the documentation

### ISSUE THREAD

**Issue by aleksijohansson** [wunderkraut/radi-cli#10]
Add minimum requirements etc. to the documentation.

**Comment by aleksijohansson** [comment]
Fix this too while we are at it https://github.com/wunderkraut/radi-project-wundertoolswrapper/issues/5.

**Comment by james-nesbitt** [comment]
https://github.com/wunderkraut/radi-project-wundertoolswrapper/issues/5 is probably complete.  This repository needs better documentation and then we are ok.
