### ISSUE TITLE
Dependency management should pull specific versions of dependencies

### ISSUE THREAD

**Issue by james-nesbitt** [wunderkraut/radi-cli#15]
Currently when the make system builds (both containerized and local), the dependencies pulled are "latest" releases.

This causes breakage when upstream versions undergo API breakage.

**Comment by james-nesbitt** [comment]
this needs review.  I have asked @aleksijohansson but I know that he is on vacation.

**Comment by james-nesbitt** [comment]
this effort is still underway.

The other repositories now all container decent fixed dependencies via vendor submodules, but this cli repo itself needs a similar update still.

**Comment by james-nesbitt** [comment]
To clarify:

- api and handler external libraries are now fixed and pinned
- cli interal libraries are not yet pinned
- the cli itself uses 1 library which is not pinned (urfave/cli)

**Comment by james-nesbitt** [comment]
#20 implemented the architecture for this. Now I only need to pick the versions.

**Comment by james-nesbitt** [comment]
Note that we did have 1 issue related to version pinning, as one of the used libraries doesn't pin it's own libraries: https://github.com/wunderkraut/radi-handler-upcloud/issues/3

**Comment by james-nesbitt** [comment]
#21 delivers the first pinned versions.

**Comment by james-nesbitt** [comment]
this needs review  ( @tharna or @aleksijohansson )

**Comment by tharna** [comment]
@james-nesbitt is there anything particular still on this one?
If the pinning is now there, and we know the exceptions so far I think everything is fine with the concept.

**Comment by james-nesbitt** [comment]
pinning at the cli level is good.  There is no version pinning in the handlers, but version pinning at this level is sufficient for now.
